### ISSUE TITLE
Can we incorporate Github's Two-Factor Authentication?

### ISSUE THREAD

**Issue by 3minus1** [3minus1/create-repo#3]
This gem fails for accounts that have 2 factor authentication enabled. Is there a way around it?

**Comment by mauricetmeyer** [comment]
One could use a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to use it with the gem, as far as I know it can be used in place for the password.

**Comment by 3minus1** [comment]
That's awesome! I didn't know about this. Thank you!
